name: Minimal Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Dependency (pip)
        run: |
          # testing tools & visualization packages
          python -m pip install invoke pytest pandas matplotlib bokeh
      - name: Customized calmap
        run: | 
         git clone https://github.com/zztin/calmap; cd calmap; python setup.py install
      - name: Packaging
        run: |
          python ${GITHUB_WORKSPACE}/setup.py install
          which ctimer

      - name: PyTest Cases
        run: |
          inv test
 
